In [4]:
import numpy as np
import random

In [3]:
def hannim(n,k,d):
    r=n-k
    p = np.zeros((1,r ),dtype = int)
    a = []
    b = []
    for i in range(1,2**r):
        p = np.zeros((1,r ),dtype = int)
        m = i
        q = 0
        for j in range(r):
            p[0,r-1-j] = m%2
            if  m%2 == 1:
                q += 1
            m = m // 2 
        if q == 0:
            continue
        elif q == 1:
            a.append(p)

        elif q != 1:
            b.append(p)
    a.reverse()
    random.shuffle(b)
    a = b+a
    
    
    c = a[0] 
    tp = 0
    for i in a:
        tp += 1
        if tp != 1:
            c = np.concatenate([c, i], axis=0) 
    
    print("标准型监督矩阵H：\n",c.T)
    c = b[0] 
    tp = 0
    for i in b:
        tp += 1
        if tp != 1:
            c = np.concatenate([c, i], axis=0) 
    
    m = np.zeros((len(c),len(c)),dtype = int)
    for i in range(len(c)):
        m[i][i]=1
    g = np.hstack((m,c))
    print("标准生成矩阵G:\n",g)
    return g

hannim(7,4,3)

标准型监督矩阵H：
 [[0 1 1 1 1 0 0]
 [1 1 0 1 0 1 0]
 [1 1 1 0 0 0 1]]
标准生成矩阵G:
 [[1 0 0 0 0 1 1]
 [0 1 0 0 1 1 1]
 [0 0 1 0 1 0 1]
 [0 0 0 1 1 1 0]]


array([[1, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 0]])